# -*- coding: utf-8 -*-
"""mongodb_casestudy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11w0JRzoOWRiGYqJaDGE6XXnFhx4wJx_4
"""

!pip install pymongo pandas matplotlib seaborn

from pymongo import MongoClient

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from pprint import pprint

# Pandas Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

# Visualization Settings
plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

plt.rcParams["figure.figsize"] = (10,6)
plt.rcParams["figure.dpi"] = 120

# Pandas Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

# Visualization Settings
plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

plt.rcParams["figure.figsize"] = (10,6)
plt.rcParams["figure.dpi"] = 120

!pip install pymongo

from pymongo import MongoClient
from urllib.parse import quote_plus

# MongoDB Atlas Credentials
username = "ankithasahukari_db_user"
password = quote_plus("Q41SzDvkTRTR0WIo")

# Connection String
uri = f"mongodb+srv://{username}:{password}@cluster0.2b4n61s.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Connect to MongoDB Atlas
client = MongoClient(uri)

# Access Database and Collection
db = client["Sample_supplies"]
sales = db["Sales"]

# Verify Connection
print("Database :", db.name)
print("Collection :", sales.name)
print("Documents :", sales.count_documents({}))

# Question 1: Total Number of Sales Transactions

total_transactions = sales.count_documents({})

print("Total Sales Transactions:", total_transactions)

# Question 1: Visualization

import matplotlib.pyplot as plt

plt.figure(figsize=(4,5))

plt.bar(["Transactions"], [total_transactions])

plt.title("Total Sales Transactions")
plt.ylabel("Number of Transactions")

plt.text(0, total_transactions + 50, str(total_transactions),
         ha='center', fontsize=12)

plt.show()

# ==============================
# Question 2: Sales Transactions by Store Location
# ==============================

pipeline = [
    {
        "$group": {
            "_id": "$storeLocation",
            "Total_Transactions": {"$sum": 1}
        }
    },
    {
        "$sort": {
            "Total_Transactions": -1
        }
    }
]

store_transactions = list(sales.aggregate(pipeline))

import pandas as pd

df_store = pd.DataFrame(store_transactions)
df_store.rename(columns={"_id": "Store Location"}, inplace=True)

df_store

# ==============================
# Question 2: Visualization
# ==============================

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.bar(df_store["Store Location"],
        df_store["Total_Transactions"])

plt.title("Sales Transactions by Store Location")
plt.xlabel("Store Location")
plt.ylabel("Number of Transactions")

plt.xticks(rotation=45)

plt.show()

# ==============================
# Question 3: Transactions by Purchase Method
# ==============================

pipeline = [
    {
        "$group": {
            "_id": "$purchaseMethod",
            "Total_Transactions": {"$sum": 1}
        }
    },
    {
        "$sort": {
            "Total_Transactions": -1
        }
    }
]

purchase_method = list(sales.aggregate(pipeline))

import pandas as pd

df_purchase = pd.DataFrame(purchase_method)
df_purchase.rename(columns={"_id": "Purchase Method"}, inplace=True)

df_purchase

# ==============================
# Question 3: Visualization
# ==============================

import matplotlib.pyplot as plt

plt.figure(figsize=(7,5))

plt.bar(df_purchase["Purchase Method"],
        df_purchase["Total_Transactions"])

plt.title("Sales Transactions by Purchase Method")
plt.xlabel("Purchase Method")
plt.ylabel("Number of Transactions")

plt.show()

# ==============================
# Question 4: Coupon vs Non-Coupon Transactions
# ==============================

pipeline = [
    {
        "$group": {
            "_id": "$couponUsed",
            "Total_Transactions": {"$sum": 1}
        }
    }
]

coupon_usage = list(sales.aggregate(pipeline))

df_coupon = pd.DataFrame(coupon_usage)

# Replace True/False with meaningful labels
df_coupon["_id"] = df_coupon["_id"].replace({
    True: "Coupon Used",
    False: "No Coupon"
})

df_coupon.rename(columns={"_id": "Coupon Status"}, inplace=True)

df_coupon

# ==============================
# Question 4: Visualization
# ==============================

import matplotlib.pyplot as plt

plt.figure(figsize=(6,6))

plt.pie(
    df_coupon["Total_Transactions"],
    labels=df_coupon["Coupon Status"],
    autopct="%1.1f%%",
    startangle=90
)

plt.title("Coupon Usage Distribution")

plt.show()

# ==============================
# Question 5: Sales Transactions by Year
# ==============================

pipeline = [
    {
        "$group": {
            "_id": {"$year": "$saleDate"},
            "Total_Transactions": {"$sum": 1}
        }
    },
    {
        "$sort": {
            "_id": 1
        }
    }
]

year_transactions = list(sales.aggregate(pipeline))

import pandas as pd

df_year = pd.DataFrame(year_transactions)
df_year.rename(columns={"_id": "Year"}, inplace=True)

df_year

# ==============================
# Question 5: Visualization
# ==============================

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.plot(df_year["Year"],
         df_year["Total_Transactions"],
         marker="o")

plt.title("Sales Transactions by Year")
plt.xlabel("Year")
plt.ylabel("Number of Transactions")

plt.grid(True)

plt.show()

# ==============================
# Question 6: Sales Transactions by Month
# ==============================

pipeline = [
    {
        "$group": {
            "_id": {"$month": "$saleDate"},
            "Total_Transactions": {"$sum": 1}
        }
    },
    {
        "$sort": {
            "_id": 1
        }
    }
]

month_transactions = list(sales.aggregate(pipeline))

import pandas as pd

df_month = pd.DataFrame(month_transactions)
df_month.rename(columns={"_id": "Month"}, inplace=True)

month_names = {
    1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr",
    5: "May", 6: "Jun", 7: "Jul", 8: "Aug",
    9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec"
}

df_month["Month"] = df_month["Month"].map(month_names)

df_month

# ==============================
# Question 6: Visualization
# ==============================

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

plt.bar(df_month["Month"],
        df_month["Total_Transactions"])

plt.title("Monthly Sales Transactions")
plt.xlabel("Month")
plt.ylabel("Number of Transactions")

plt.show()

# ==============================
# Question 7: Unique Products
# ==============================

pipeline = [
    {
        "$unwind": "$items"
    },
    {
        "$group": {
            "_id": "$items.name"
        }
    },
    {
        "$sort": {
            "_id": 1
        }
    }
]

products = list(sales.aggregate(pipeline))

import pandas as pd

df_products = pd.DataFrame(products)
df_products.rename(columns={"_id": "Product Name"}, inplace=True)

print("Total Unique Products:", len(df_products))
df_products

# ==============================
# Question 7: Visualization
# ==============================

import matplotlib.pyplot as plt

plt.figure(figsize=(5,5))

plt.bar(["Unique Products"], [len(df_products)])

plt.title("Total Unique Products")
plt.ylabel("Count")

plt.text(0, len(df_products)+0.2,
         str(len(df_products)),
         ha='center',
         fontsize=12)

plt.show()

# ==============================
# Question 8: Average Customer Satisfaction
# ==============================

pipeline = [
    {
        "$group": {
            "_id": None,
            "Average_Rating": {
                "$avg": "$customer.satisfaction"
            }
        }
    }
]

rating = list(sales.aggregate(pipeline))

average_rating = round(rating[0]["Average_Rating"], 2)

print("Average Customer Satisfaction Rating:", average_rating)

# ==============================
# Question 8: Visualization
# ==============================

import matplotlib.pyplot as plt

plt.figure(figsize=(5,5))

plt.bar(["Average Rating"], [average_rating])

plt.title("Average Customer Satisfaction Rating")
plt.ylabel("Rating (Out of 5)")

plt.ylim(0, 5)

plt.text(0,
         average_rating + 0.05,
         average_rating,
         ha='center',
         fontsize=12)

plt.show()

# ==============================
# Question 9: Highest Total Quantity Sold by Product
# ==============================

pipeline = [
    {
        "$unwind": "$items"
    },
    {
        "$group": {
            "_id": "$items.name",
            "Total_Quantity_Sold": {
                "$sum": "$items.quantity"
            }
        }
    },
    {
        "$sort": {
            "Total_Quantity_Sold": -1
        }
    }
]

quantity_sold = list(sales.aggregate(pipeline))

import pandas as pd

df_quantity = pd.DataFrame(quantity_sold)
df_quantity.rename(columns={"_id": "Product Name"}, inplace=True)

df_quantity

# ==============================
# Question 9: Visualization
# ==============================

import matplotlib.pyplot as plt

top10 = df_quantity.head(10)

plt.figure(figsize=(10,6))

plt.bar(top10["Product Name"],
        top10["Total_Quantity_Sold"])

plt.title("Top 10 Products by Quantity Sold")
plt.xlabel("Product Name")
plt.ylabel("Total Quantity Sold")

plt.xticks(rotation=45)

plt.show()

# ==============================
# Question 10: Highest Sales Revenue by Product
# ==============================

pipeline = [
    {
        "$unwind": "$items"
    },
    {
        "$group": {
            "_id": "$items.name",
            "Total_Revenue": {
                "$sum": {
                    "$multiply": [
                        "$items.quantity",
                        "$items.price"
                    ]
                }
            }
        }
    },
    {
        "$sort": {
            "Total_Revenue": -1
        }
    }
]

revenue = list(sales.aggregate(pipeline))

df_revenue = pd.DataFrame(revenue)
df_revenue.rename(columns={"_id": "Product Name"}, inplace=True)

df_revenue

# ==============================
# Question 10: Visualization
# ==============================

import matplotlib.pyplot as plt

# Convert Decimal128 to float
df_revenue["Total_Revenue"] = df_revenue["Total_Revenue"].apply(lambda x: float(x.to_decimal()))

# Top 10 products
top10 = df_revenue.head(10)

plt.figure(figsize=(10,6))

plt.bar(top10["Product Name"],
        top10["Total_Revenue"])

plt.title("Top 10 Products by Sales Revenue")
plt.xlabel("Product Name")
plt.ylabel("Total Revenue")

plt.xticks(rotation=45)

plt.show()

# ==============================
# Question 11: Total Sales Revenue by Store Location
# ==============================

pipeline = [
    {
        "$unwind": "$items"
    },
    {
        "$group": {
            "_id": "$storeLocation",
            "Total_Revenue": {
                "$sum": {
                    "$multiply": [
                        "$items.quantity",
                        "$items.price"
                    ]
                }
            }
        }
    },
    {
        "$sort": {
            "Total_Revenue": -1
        }
    }
]

store_revenue = list(sales.aggregate(pipeline))

import pandas as pd

df_store_revenue = pd.DataFrame(store_revenue)
df_store_revenue.rename(columns={"_id": "Store Location"}, inplace=True)

# Convert Decimal128 to float
df_store_revenue["Total_Revenue"] = df_store_revenue["Total_Revenue"].apply(
    lambda x: float(x.to_decimal())
)

df_store_revenue

# ==============================
# Question 11: Visualization
# ==============================

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.bar(df_store_revenue["Store Location"],
        df_store_revenue["Total_Revenue"])

plt.title("Total Sales Revenue by Store Location")
plt.xlabel("Store Location")
plt.ylabel("Total Revenue")

plt.xticks(rotation=45)

plt.show()

# ==============================
# Question 12: Total Revenue by Purchase Method
# ==============================

pipeline = [
    {
        "$unwind": "$items"
    },
    {
        "$group": {
            "_id": "$purchaseMethod",
            "Total_Revenue": {
                "$sum": {
                    "$multiply": [
                        "$items.quantity",
                        "$items.price"
                    ]
                }
            }
        }
    },
    {
        "$sort": {
            "Total_Revenue": -1
        }
    }
]

purchase_revenue = list(sales.aggregate(pipeline))

df_purchase_revenue = pd.DataFrame(purchase_revenue)
df_purchase_revenue.rename(columns={"_id": "Purchase Method"}, inplace=True)

# Convert Decimal128 to float
df_purchase_revenue["Total_Revenue"] = df_purchase_revenue["Total_Revenue"].apply(
    lambda x: float(x.to_decimal())
)

df_purchase_revenue

# ==============================
# Question 12: Visualization
# ==============================

import matplotlib.pyplot as plt

plt.figure(figsize=(7,5))

plt.bar(df_purchase_revenue["Purchase Method"],
        df_purchase_revenue["Total_Revenue"])

plt.title("Total Sales Revenue by Purchase Method")
plt.xlabel("Purchase Method")
plt.ylabel("Total Revenue")

plt.show()

# ==============================
# Question 13: Average Transaction Value by Store Location
# ==============================

pipeline = [
    {
        "$unwind": "$items"
    },
    {
        "$group": {
            "_id": {
                "transaction_id": "$_id",
                "store": "$storeLocation"
            },
            "Transaction_Value": {
                "$sum": {
                    "$multiply": [
                        "$items.quantity",
                        "$items.price"
                    ]
                }
            }
        }
    },
    {
        "$group": {
            "_id": "$_id.store",
            "Average_Transaction_Value": {
                "$avg": "$Transaction_Value"
            }
        }
    },
    {
        "$sort": {
            "Average_Transaction_Value": -1
        }
    }
]

avg_transaction = list(sales.aggregate(pipeline))

import pandas as pd

df_avg_transaction = pd.DataFrame(avg_transaction)
df_avg_transaction.rename(columns={"_id": "Store Location"}, inplace=True)

# Convert Decimal128 to float
df_avg_transaction["Average_Transaction_Value"] = (
    df_avg_transaction["Average_Transaction_Value"]
    .apply(lambda x: float(x.to_decimal()))
)

df_avg_transaction

# ==============================
# Question 13: Visualization
# ==============================

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.bar(
    df_avg_transaction["Store Location"],
    df_avg_transaction["Average_Transaction_Value"]
)

plt.title("Average Transaction Value by Store Location")
plt.xlabel("Store Location")
plt.ylabel("Average Transaction Value")

plt.xticks(rotation=45)

plt.show()

# ==============================
# Question 14: Product Revenue (Coupon Used)
# ==============================

pipeline = [
    {
        "$match": {
            "couponUsed": True
        }
    },
    {
        "$unwind": "$items"
    },
    {
        "$group": {
            "_id": "$items.name",
            "Total_Revenue": {
                "$sum": {
                    "$multiply": [
                        "$items.quantity",
                        "$items.price"
                    ]
                }
            }
        }
    },
    {
        "$sort": {
            "Total_Revenue": -1
        }
    }
]

coupon_revenue = list(sales.aggregate(pipeline))

df_coupon_revenue = pd.DataFrame(coupon_revenue)
df_coupon_revenue.rename(columns={"_id": "Product Name"}, inplace=True)

# Convert Decimal128 to float
df_coupon_revenue["Total_Revenue"] = (
    df_coupon_revenue["Total_Revenue"]
    .apply(lambda x: float(x.to_decimal()))
)

df_coupon_revenue

# ==============================
# Question 14: Visualization
# ==============================

import matplotlib.pyplot as plt

top10 = df_coupon_revenue.head(10)

plt.figure(figsize=(10,6))

plt.bar(
    top10["Product Name"],
    top10["Total_Revenue"]
)

plt.title("Top 10 Products by Revenue (Coupon Used)")
plt.xlabel("Product Name")
plt.ylabel("Total Revenue")

plt.xticks(rotation=45)

plt.show()

# ==============================
# Question 15: Average Selling Price of Each Product
# ==============================

pipeline = [
    {
        "$unwind": "$items"
    },
    {
        "$group": {
            "_id": "$items.name",
            "Average_Price": {
                "$avg": "$items.price"
            }
        }
    },
    {
        "$sort": {
            "Average_Price": -1
        }
    }
]

avg_price = list(sales.aggregate(pipeline))

import pandas as pd

df_avg_price = pd.DataFrame(avg_price)
df_avg_price.rename(columns={"_id": "Product Name"}, inplace=True)

# Convert Decimal128 to float
df_avg_price["Average_Price"] = df_avg_price["Average_Price"].apply(
    lambda x: float(x.to_decimal())
)

df_avg_price

# ==============================
# Question 15: Visualization
# ==============================

import matplotlib.pyplot as plt

top10 = df_avg_price.head(10)

plt.figure(figsize=(10,6))

plt.bar(
    top10["Product Name"],
    top10["Average_Price"]
)

plt.title("Top 10 Products by Average Selling Price")
plt.xlabel("Product Name")
plt.ylabel("Average Selling Price")

plt.xticks(rotation=45)

plt.show()

# ==============================
# Question 16: Total Value of Each Sales Transaction
# ==============================

pipeline = [
    {
        "$unwind": "$items"
    },
    {
        "$group": {
            "_id": "$_id",
            "Transaction_Value": {
                "$sum": {
                    "$multiply": [
                        "$items.quantity",
                        "$items.price"
                    ]
                }
            }
        }
    },
    {
        "$sort": {
            "Transaction_Value": -1
        }
    }
]

transaction_value = list(sales.aggregate(pipeline))

df_transaction = pd.DataFrame(transaction_value)

# Convert Decimal128 to float
df_transaction["Transaction_Value"] = df_transaction["Transaction_Value"].apply(
    lambda x: float(x.to_decimal())
)

df_transaction.head(10)

# ==============================
# Question 16: Visualization
# ==============================

import matplotlib.pyplot as plt

top10 = df_transaction.head(10)

plt.figure(figsize=(10,6))

plt.bar(
    top10.index.astype(str),
    top10["Transaction_Value"]
)

plt.title("Top 10 Highest Value Transactions")
plt.xlabel("Transaction")
plt.ylabel("Transaction Value")

plt.xticks(rotation=45)

plt.show()

# ==============================
# Question 17: High Value vs Low Value Transactions
# ==============================

pipeline = [
    {
        "$unwind": "$items"
    },
    {
        "$group": {
            "_id": "$_id",
            "Transaction_Value": {
                "$sum": {
                    "$multiply": [
                        "$items.quantity",
                        "$items.price"
                    ]
                }
            }
        }
    },
    {
        "$project": {
            "Transaction_Value": 1,
            "Category": {
                "$cond": {
                    "if": {"$gte": ["$Transaction_Value", 500]},
                    "then": "High Value",
                    "else": "Low Value"
                }
            }
        }
    },
    {
        "$group": {
            "_id": "$Category",
            "Total_Transactions": {"$sum": 1}
        }
    }
]

value_category = list(sales.aggregate(pipeline))

import pandas as pd

df_value_category = pd.DataFrame(value_category)
df_value_category.rename(columns={"_id": "Category"}, inplace=True)

df_value_category

# ==============================
# Question 17: Visualization
# ==============================

import matplotlib.pyplot as plt

plt.figure(figsize=(6,5))

plt.bar(
    df_value_category["Category"],
    df_value_category["Total_Transactions"]
)

plt.title("High Value vs Low Value Transactions")
plt.xlabel("Transaction Category")
plt.ylabel("Number of Transactions")

plt.show()

# ==============================
# Question 18: Transaction Value Distribution
# ==============================

pipeline = [
    {
        "$unwind": "$items"
    },
    {
        "$group": {
            "_id": "$_id",
            "Transaction_Value": {
                "$sum": {
                    "$multiply": [
                        "$items.quantity",
                        "$items.price"
                    ]
                }
            }
        }
    },
    {
        "$bucket": {
            "groupBy": "$Transaction_Value",
            "boundaries": [0, 100, 300, 500, 1000, 5000],
            "default": "Above 5000",
            "output": {
                "Count": {"$sum": 1}
            }
        }
    }
]

transaction_distribution = list(sales.aggregate(pipeline))

df_distribution = pd.DataFrame(transaction_distribution)

# Convert Decimal128 bucket labels if present
df_distribution["_id"] = df_distribution["_id"].astype(str)

df_distribution

# ==============================
# Question 18: Visualization
# ==============================

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.bar(
    df_distribution["_id"],
    df_distribution["Count"]
)

plt.title("Transaction Value Distribution")
plt.xlabel("Transaction Value Range")
plt.ylabel("Number of Transactions")

plt.xticks(rotation=45)

plt.show()

# ==============================
# Question 19: MongoDB $facet Aggregation
# ==============================

pipeline = [
    {
        "$facet": {
            "Purchase_Method": [
                {
                    "$group": {
                        "_id": "$purchaseMethod",
                        "Transactions": {"$sum": 1}
                    }
                }
            ],
            "Store_Location": [
                {
                    "$group": {
                        "_id": "$storeLocation",
                        "Transactions": {"$sum": 1}
                    }
                }
            ],
            "Coupon_Usage": [
                {
                    "$group": {
                        "_id": "$couponUsed",
                        "Transactions": {"$sum": 1}
                    }
                }
            ]
        }
    }
]

facet_result = list(sales.aggregate(pipeline))

from pprint import pprint

pprint(facet_result)

# ==============================
# Question 20: Executive Dashboard
# ==============================

total_transactions = sales.count_documents({})

pipeline = [
    {"$unwind": "$items"},
    {
        "$group": {
            "_id": None,
            "Total_Revenue": {
                "$sum": {
                    "$multiply": [
                        "$items.quantity",
                        "$items.price"
                    ]
                }
            },
            "Average_Satisfaction": {
                "$avg": "$customer.satisfaction"
            }
        }
    }
]

dashboard = list(sales.aggregate(pipeline))[0]

total_revenue = float(dashboard["Total_Revenue"].to_decimal())
average_rating = round(dashboard["Average_Satisfaction"], 2)

print("Total Transactions :", total_transactions)
print("Total Revenue      :", round(total_revenue, 2))
print("Average Rating     :", average_rating)

# ==============================
# Question 20: Dashboard
# ==============================

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(10,5))
ax.axis("off")

dashboard_text = f"""
EXECUTIVE BUSINESS DASHBOARD

Total Transactions : {total_transactions}

Total Revenue      : ${total_revenue:,.2f}

Average Rating     : {average_rating}/5
"""

ax.text(
    0.02,
    0.98,
    dashboard_text,
    fontsize=16,
    verticalalignment="top",
    bbox=dict(facecolor="lightblue", alpha=0.5)
)

plt.show()

